apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      AppName: service-a
  template:
    metadata:
      labels:
        AppName: service-a
    spec:
      containers:
        - name: service-a
          image: hashicorp/http-echo
          args:
            - "-text=service-a(novinho)"
          ports:
            - name: tcp-5678
              containerPort: 5678
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600